In [1]:
from numpy import genfromtxt
data = genfromtxt('data/data.csv', delimiter=',')
y_data = data.T[:1].T
x_data = data.T[1:].T

print(f"Shape of x_data: {x_data.shape}")
print(f"Shape of y_data: {y_data.shape}")



Shape of x_data: (1127, 8)
Shape of y_data: (1127, 1)


In [2]:
#Seperation of Data into 3 sets, train, validation, and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2)

print(f"Shape of x_train: {x_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of x_test: {x_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

print(x_train)


Shape of x_train: (901, 8)
Shape of y_train: (901, 1)
Shape of x_test: (226, 8)
Shape of y_test: (226, 1)
[[ 31669.  28103.   3930. ...   7567.   3793.   3755.]
 [100336.  23492.  11212. ...   6527.   1824.   1046.]
 [ 99374. 201959.  10137. ...   3380.   3823.   1325.]
 ...
 [ 73464.  28197.   7264. ...   3558.    853.   1767.]
 [ 23468.  18147.   4406. ...   4301.   3464.   2486.]
 [203626.  11084.   3150. ...   1535.   1384.    632.]]


In [19]:
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=20000, 
                               random_state=48, 
                               max_features = 'sqrt',
                               n_jobs=-1, verbose = 1,oob_score=False,max_depth=6)

# Fit on training data
model.fit(x_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:    2.2s
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed:    3.2s
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed:    4.3s
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed:    5.7s
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed:    7.2s
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed:    9.2s
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed:   11.4s
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed:   15.9s
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed:   18.5s
[Parallel(n_jobs=-1)]: Done 11242 tasks  

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20000,
                       n_jobs=-1, oob_score=False, random_state=48, verbose=1,
                       warm_start=False)

In [20]:
import numpy as np
n_nodes = []
max_depths = []

for ind_tree in model.estimators_:
    n_nodes.append(ind_tree.tree_.node_count)
    max_depths.append(ind_tree.tree_.max_depth)
    
print(f'Average number of nodes {int(np.mean(n_nodes))}')
print(f'Average maximum depth {int(np.mean(max_depths))}')


Average number of nodes 42
Average maximum depth 5


In [22]:
y_pred=model.predict(x_test)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 442 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed:    0.4s
[Parallel(n_jobs=4)]: Done 1242 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done 1792 tasks      | elapsed:    0.6s
[Parallel(n_jobs=4)]: Done 2442 tasks      | elapsed:    0.8s
[Parallel(n_jobs=4)]: Done 3192 tasks      | elapsed:    1.0s
[Parallel(n_jobs=4)]: Done 4042 tasks      | elapsed:    1.2s
[Parallel(n_jobs=4)]: Done 4992 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done 6042 tasks      | elapsed:    1.8s
[Parallel(n_jobs=4)]: Done 7192 tasks      | elapsed:    2.1s
[Parallel(n_jobs=4)]: Done 8442 tasks      | elapsed:    2.3s
[Parallel(n_jobs=4)]: Done 9792 tasks      | elapsed:    2.7s
[Parallel(n_jobs=4)]: Done 11242 tasks      | elapsed:  